Imports

In [3]:
import numpy as np
import pandas as pd

#sklearn tools
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split

#classifiers
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

#Evaluate
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

Loading Dataset

In [4]:
df = pd.read_csv("/content/Crop_recommendation.csv")
df

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

Encoding

In [5]:
df['label'].value_counts()

label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
jute           100
coffee         100
Name: count, dtype: int64

In [6]:
len(df['label'].value_counts())

22

In [7]:
encoder = LabelEncoder()
df['Label'] = encoder.fit_transform(df['label'])
df

N   P   K  temperature   humidity        ph    rainfall   label  Label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice     20
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice     20
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice     20
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice     20
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice     20
...   ...  ..  ..          ...        ...       ...         ...     ...    ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee      5
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee      5
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee      5
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee      5
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee      5

[2200 rows x 9 columns]

Scaling : Normalization

In [8]:
# Numeric columns Selecting to normalise
numeric_cols = ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']

#Initializing scaler
scaler = MinMaxScaler()

#Fit transform the numeric columns
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

df.head()

N         P      K  temperature  humidity        ph  rainfall label  \
0  0.642857  0.264286  0.190     0.345886  0.790267  0.466264  0.656458  rice   
1  0.607143  0.378571  0.180     0.371445  0.770633  0.549480  0.741675  rice   
2  0.428571  0.357143  0.195     0.406854  0.793977  0.674219  0.875710  rice   
3  0.528571  0.214286  0.175     0.506901  0.768751  0.540508  0.799905  rice   
4  0.557143  0.264286  0.185     0.324378  0.785626  0.641291  0.871231  rice   

   Label  
0     20  
1     20  
2     20  
3     20  
4     20

Train-Test Split

In [9]:
X = df.drop('label', axis=1)
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

Training, Testing with Multiple Classifiers

In [10]:
models = {
    "lg": LogisticRegression()
}

for name, model in models.items():
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)

  print(f"Model name:\n", name)
  print('Confusion matrix:\n', confusion_matrix(y_test, y_pred))
  print('Accuracy score:\n', accuracy_score(y_test, y_pred))
  print('Classification report:\n', classification_report(y_test, y_pred))

Model name:
 lg
Confusion matrix:
 [[28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0]

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
models = {
    "rf": RandomForestClassifier()
}

for name, model in models.items():
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)

  print(f"Model name:\n", name)
  print('Confusion matrix:\n', confusion_matrix(y_test, y_pred))
  print('Accuracy score:\n', accuracy_score(y_test, y_pred))
  print('Classification report:\n', classification_report(y_test, y_pred))

Model name:
 rf
Confusion matrix:
 [[28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0]

Selecting Best Model

In [12]:
model = {
    "gb": GradientBoostingClassifier()
}

for name, model in models.items():
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)

  print(f"Model name:\n", name)
  print('Confusion matrix:\n', confusion_matrix(y_test, y_pred))
  print('Accuracy score:\n', accuracy_score(y_test, y_pred))
  print('Classification report:\n', classification_report(y_test, y_pred))

Model name:
 rf
Confusion matrix:
 [[28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0]

In [13]:
model_gb = GradientBoostingClassifier()
model_gb.fit(X_train, y_train)
y_pred = model_gb.predict(X_test)

name = "GradientBoostingClassifier"

print(f"Model name:\n", name)
print('Confusion matrix:\n', confusion_matrix(y_test, y_pred))
print('Accuracy score:\n', accuracy_score(y_test, y_pred))
print('Classification report:\n', classification_report(y_test, y_pred))

Model name:
 GradientBoostingClassifier
Confusion matrix:
 [[28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 17  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 15 

Saving Model, Encoder and Scaler for production (Pickle files)

In [16]:
import pickle
pickle.dump(model_gb, open('model.pkl', 'wb'))
pickle.dump(model_gb, open('encoder.pkl', 'wb'))
pickle.dump(scaler, open('scaler.pkl','wb'))

features = ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']
X = df[features]
y = df['label']

model.fit(X, y)

def predict_crop(N, P, K, temperature, humidity, ph, rainfall):
    input_df = pd.DataFrame([{
        'N': N,
        'P': P,
        'K': K,
        'temperature': temperature,
        'humidity': humidity,
        'ph': ph,
        'rainfall': rainfall
    }])

    # Ensure the columns are in the same order as training
    input_df = input_df[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']]

    prediction = model.predict(input_df)
    return prediction[0]

result = predict_crop(80, 60, 40, 30.0, 70.0, 6.8, 100.0)
print('Recommended crop:', result)

Recommended crop: apple


In [17]:
import sklearn
print(sklearn.__version__)

1.6.1
